apiVersion: v1
kind: Service
metadata:
  name: bin-sohamsen-me
  labels:
    app: bin-sohamsen-me
    service: bin-sohamsen-me
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: bin-sohamsen-me
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-sohamsen-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bin-sohamsen-me
  template:
    metadata:
      labels:
        app: bin-sohamsen-me
    spec:
      containers:
        - image: registry.sohamsen.me/ghostdev/yabin:latest
          imagePullPolicy: IfNotPresent
          name: bin-sohamsen-me
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: yabin-config
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "1"
      imagePullSecrets:
      - name: registry-sohamsen-me
      restartPolicy: Always
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bin-sohamsen-me
spec:
  hosts:
    - 'bin.sohamsen.me'
  gateways:
    - prod/sohamsen-me-gateway
  http:
    - route:
        - destination:
            host: bin-sohamsen-me
            port:
              number: 80
